services:
  front: &front
    container_name: front
    build:
      dockerfile: ./docker/front/Dockerfile
      context: . # https://qiita.com/sam8helloworld/items/e7fffa9afc82aea68a7a
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "3001:3001"
      - "24678:24678" # ホットリロード用
    command: [npm, run, dev, --, -p, "3001"]
    depends_on:
      - db

  prisma-studio:
    <<: *front
    container_name: prisma-studio
    ports:
      - "${PRISMA_STUDIO_PORT}:5555"
    environment:
      - HOST=0.0.0.0
    command:
      [
        "npx",
        "prisma",
        "studio",
        "--port",
        "${PRISMA_STUDIO_PORT}",
        "--browser",
        "none",
      ]

  db:
    container_name: prisma-postgres
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - topic-pick:/var/lib/postgresql/data

volumes:
  topic-pick:
