// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", // https://www.prisma.io/docs/orm/prisma-migrate/workflows/seeding
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
